name: Развертывание проекта

on:
  push:
    tags:
      - '*'
  workflow_dispatch:


jobs:
  validate-ref:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.validate.outputs.version }}
      version_type: ${{ steps.validate.outputs.version_type }}
      create-release: ${{ steps.validate.outputs.create-release }}
      is_valid: ${{ steps.validate.outputs.is_valid }}
    steps:
      - name: Проверка
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Опредеделение версии
        id: validate
        run: |
          # Определяем, что было выбрано: branch или tag
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            # Это тег
            SEGMENTS=$(echo "$GITHUB_REF" | tr '.' '\n' | wc -l)
            if [ "$SEGMENTS" -le 3 ]; then
              echo "create-release=true" >> $GITHUB_OUTPUT
            else
              echo "create-release=false" >> $GITHUB_OUTPUT
            fi
            VERSION=${GITHUB_REF#refs/tags/}
            VERSION_TYPE="tag"
          else
            # Это ветка
            VERSION=${GITHUB_REF#refs/heads/}
            VERSION_TYPE="branch"
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version_type=$VERSION_TYPE" >> $GITHUB_OUTPUT
          echo "is_valid=true" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: validate-ref
    if: needs.validate-ref.outputs.is_valid == 'true'
    steps:
      - name: Проверка
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.ref || github.ref }}

      - name: Отправка .production
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".production"
          target: "/tmp/.env"

      - name: Деплой
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x ~/deploy.sh
            ~/deploy.sh ${{ github.repository_owner }} ${{ github.event.repository.name }} ${{ needs.validate-ref.outputs.version_type }} ${{ needs.validate-ref.outputs.version }}
  create-release:
    runs-on: ubuntu-latest
    needs: validate-ref
    if: needs.validate-ref.outputs.create-release == 'true'
    steps:
      - name: Создание релиза
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.validate-ref.outputs.version }}
          name: Релиз ${{ needs.validate-ref.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}